// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: operation_request.proto

package operationsbus

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationName       string                 `protobuf:"bytes,1,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`                   // Name of the operation being processed. Used to match the ApiOperation with the right implementation.
	ApiVersion          string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`                            // Specifies the version of the API the operation is associated with, ensuring compatibility.
	RetryCount          int32                  `protobuf:"varint,3,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`                           // Tracks the number of retries of the operation to prevent infinite looping or special logic around retries.
	OperationId         string                 `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`                         // A unique identifier for the operation.
	EntityId            string                 `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`                                  // A unique identifier for the entity (resource) the operation is acting on, used with EntityType to ensure we have selected the right entity.
	EntityType          string                 `protobuf:"bytes,6,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`                            // Specified the type of entity the operation is acting on, used with EntityId to ensure we have selected the right Entity.
	ExpirationTimestamp *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=expiration_timestamp,json=expirationTimestamp,proto3" json:"expiration_timestamp,omitempty"` // Defines when the operation should expire and prevent execution, should it have passed this date.
	Body                []byte                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`                                                          // Contains request payload or data needed for the operation in HTTP operations.
	HttpMethod          string                 `protobuf:"bytes,9,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`                            // Indicated the GGPT method if the operation requires HTTP-based communication.
	Extension           *any1.Any              `protobuf:"bytes,10,opt,name=extension,proto3" json:"extension,omitempty"`                                               // An optional and flexible field to add any data the user may require.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_operation_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_request_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *OperationRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OperationRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *OperationRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *OperationRequest) GetExpirationTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

func (x *OperationRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OperationRequest) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *OperationRequest) GetExtension() *any1.Any {
	if x != nil {
		return x.Extension
	}
	return nil
}

var File_operation_request_proto protoreflect.FileDescriptor

const file_operation_request_proto_rawDesc = "" +
	"\n" +
	"\x17operation_request.proto\x12\roperationsbus\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x94\x03\n" +
	"\x10OperationRequest\x12%\n" +
	"\x0eoperation_name\x18\x01 \x01(\tR\roperationName\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1f\n" +
	"\vretry_count\x18\x03 \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x06 \x01(\tR\n" +
	"entityType\x12M\n" +
	"\x14expiration_timestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13expirationTimestamp\x12\x12\n" +
	"\x04body\x18\b \x01(\fR\x04body\x12\x1f\n" +
	"\vhttp_method\x18\t \x01(\tR\n" +
	"httpMethod\x122\n" +
	"\textension\x18\n" +
	" \x01(\v2\x14.google.protobuf.AnyR\textensionB Z\x1eoperationsbus/operationrequestb\x06proto3"

var (
	file_operation_request_proto_rawDescOnce sync.Once
	file_operation_request_proto_rawDescData []byte
)

func file_operation_request_proto_rawDescGZIP() []byte {
	file_operation_request_proto_rawDescOnce.Do(func() {
		file_operation_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_request_proto_rawDesc), len(file_operation_request_proto_rawDesc)))
	})
	return file_operation_request_proto_rawDescData
}

var file_operation_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_operation_request_proto_goTypes = []any{
	(*OperationRequest)(nil),    // 0: operationsbus.OperationRequest
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*any1.Any)(nil),            // 2: google.protobuf.Any
}
var file_operation_request_proto_depIdxs = []int32{
	1, // 0: operationsbus.OperationRequest.expiration_timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: operationsbus.OperationRequest.extension:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_operation_request_proto_init() }
func file_operation_request_proto_init() {
	if File_operation_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_request_proto_rawDesc), len(file_operation_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operation_request_proto_goTypes,
		DependencyIndexes: file_operation_request_proto_depIdxs,
		MessageInfos:      file_operation_request_proto_msgTypes,
	}.Build()
	File_operation_request_proto = out.File
	file_operation_request_proto_goTypes = nil
	file_operation_request_proto_depIdxs = nil
}
